### ISSUE TITLE
Missing /Build/ folder in /vendor/justintadlock/hybrid-breadcrumbs/src

### ISSUE THREAD

**Issue by isotrope** [skyshab/taproot#2]
Without the folder:
`( ! ) Fatal error: Uncaught Error: Class '\Hybrid\Breadcrumbs\Build\Network' not found in /var/www/html/wp-content/themes/taproot/vendor/justintadlock/hybrid-breadcrumbs/src/Breadcrumbs.php on line 347
( ! ) Error: Class '\Hybrid\Breadcrumbs\Build\Network' not found in /var/www/html/wp-content/themes/taproot/vendor/justintadlock/hybrid-breadcrumbs/src/Breadcrumbs.php on line 347`

**Comment by skyshab** [comment]
"build" somehow got added to .gitignore. Thanks for pointing this out!

**Comment by skyshab** [comment]
fixed in 1.0.1
